[workspace]
resolver = "3"
members = ["crates/mk-codec", "crates/mk-cli"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Unlicense"
repository = "https://github.com/bg002h/mnemonic-key"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2
